version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Giữ node_modules trong container
    environment:
      - WATCHPACK_POLLING=true # Kích hoạt hot reload
    stdin_open: true
    tty: true
    command: ["yarn", "start"]
